/**
 * 🛡️ CENTRALIZED ERROR CODES
 * Standardized machine-readable strings for API errors.
 * Synced with backend/src/constants/error-codes.ts
 */
export enum ErrorCode {
  // --- Auth & Access ---
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",

  // --- Data Integrity ---
  STALE_VERSION_CONFLICT = "STALE_VERSION_CONFLICT",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE",

  // --- AI & Quotas ---
  INSUFFICIENT_QUOTA = "INSUFFICIENT_QUOTA",
  AI_SERVICE_UNSTABLE = "AI_SERVICE_UNSTABLE",
  AI_GENERATION_FAILED = "AI_SERVICE_FAILED",

  // --- Payments ---
  PAYMENT_REQUIRED = "PAYMENT_REQUIRED",
  STRIPE_CONFIG_ERROR = "STRIPE_CONFIG_ERROR",

  // --- Infrastructure ---
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR",
  EXTERNAL_API_ERROR = "EXTERNAL_API_ERROR",
}
