import React from "react";
import { ShieldAlert } from "lucide-react";
import { useTranslation } from "react-i18next";

/**
 * 🛡️ AI DISCLAIMER
 * Mandatory footer for all AI-generated content (Law 151 & Liability).
 */
export const AiDisclaimer: React.FC = () => {
  const { t } = useTranslation();

  return (
    <div className="mt-6 pt-4 border-t border-dashed border-primary/10 flex items-start gap-3 opacity-60 grayscale hover:opacity-100 hover:grayscale-0 transition-all duration-500">
      <ShieldAlert className="h-4 w-4 text-primary shrink-0 mt-0.5" />
      <p className="text-[10px] font-medium leading-relaxed text-start">
        <span className="font-black uppercase tracking-tighter text-primary">AI-Generated Draft:</span>{" "}
        {t(
          "ai.disclaimer.text",
          "This content was generated by Tablawy OS AI. It requires human verification before being entered into official academic records. Protected under Law 151/2020 (PII Scrubbing Active)."
        )}
      </p>
    </div>
  );
};
