import { 
  Home, 
  BookOpen, 
  Building2, 
  Calendar, 
  Sparkles, 
  UserPlus, 
  ClipboardCheck, 
  FileQuestion,
  BrainCircuit,
  ShieldCheck,
  LayoutGrid,
  FileText,
  Send,
  CheckSquare,
  Library,
  MessageSquare,
  FolderOpen,
  Bell,
  TrendingUp,
  Activity,
  UserCircle,
  CalendarClock,
  CalendarDays,
  Briefcase
} from "lucide-react";
import { ResourceProps } from "@refinedev/core";

export const resources: ResourceProps[] = [
  { name: "dashboard", list: "/", meta: { label: "Dashboard", icon: <Home /> } },
  { name: "classes", list: "/classes", create: "/classes/create", edit: "/classes/edit/:id", show: "/classes/show/:id", meta: { label: "Classes", icon: <LayoutGrid /> } },
  { name: "ai-study-lab", list: "/ai-study-lab", meta: { label: "AI Study Lab", icon: <BrainCircuit /> } },
  { name: "study-planner", list: "/study-planner", meta: { label: "Study Planner", icon: <CalendarDays /> } },
  { name: "ai-assistant", list: "/ai-assistant", meta: { label: "AI Assistant", icon: <Sparkles /> } },
  { name: "calendar", list: "/calendar", meta: { label: "Calendar", icon: <Calendar /> } },
  { name: "academic-terms", list: "/admin/terms", meta: { label: "Academic Terms", icon: <CalendarClock /> } },
  { name: "subjects", list: "/subjects", create: "/subjects/create", edit: "/subjects/edit/:id", meta: { label: "Subjects", icon: <BookOpen /> } },
  { name: "departments", list: "/departments", create: "/departments/create", edit: "/departments/edit/:id", meta: { label: "Departments", icon: <Building2 /> } },
  { name: "users", list: "/users", create: "/users/create", edit: "/users/edit/:id", show: "/users/show/:id", meta: { label: "Users", icon: <ShieldCheck /> } },
  { name: "portfolio", list: "/portfolio", meta: { label: "My Portfolio", icon: <UserCircle /> } },
  { name: "report-card", list: "/student/report-card", meta: { label: "Report Card", icon: <FileText /> } },
  { name: "profile-requests", list: "/profile-requests", meta: { label: "Profile Requests", icon: <ClipboardCheck /> } },
  { name: "activity-log", list: "/activity-log", meta: { label: "Activity Log", icon: <Activity /> } },
  { name: "teacher-applications", list: "/teacher-applications", meta: { label: "Teacher Apps", icon: <Briefcase /> } },
  { name: "enrollments", list: "/enrollments", meta: { label: "Enrollments", icon: <UserPlus /> } },
  { name: "assignments", list: "/assignments", create: "/assignments/create", show: "/assignments/show/:id", meta: { label: "Assignments", icon: <FileText /> } },
  { name: "submissions", list: "/submissions", show: "/submissions/show/:id", meta: { label: "Submissions", icon: <Send /> } },
  { name: "attendance", list: "/attendance", meta: { label: "Attendance", icon: <CheckSquare /> } },
  { name: "quizzes", list: "/quizzes", create: "/quizzes/create", show: "/quizzes/show/:id", meta: { label: "Quizzes", icon: <FileQuestion /> } },
  { name: "modules", list: "/modules", meta: { label: "Modules", icon: <Library /> } },
  { name: "discussions", list: "/discussions", meta: { label: "Discussions", icon: <MessageSquare /> } },
  { name: "resources", list: "/resources", meta: { label: "Resources", icon: <FolderOpen /> } },
  { name: "notifications", list: "/notifications", meta: { label: "Notifications", icon: <Bell /> } },
  { name: "progress", list: "/progress", meta: { label: "Progress", icon: <TrendingUp /> } },
];
